from typing import Protocol

from app.domain.models import Activity, ConditionReport, WorkoutProposal


class StravaPort(Protocol):
    async def get_activity(self, activity_id: str, athlete_id: str) -> Activity: ...
    async def append_description(self, activity_id: str, text: str) -> None: ...


class LinePort(Protocol):
    async def request_condition(self, athlete_id: str, activity: Activity) -> None: ...
    async def send_proposal(
        self, athlete_id: str, proposal: WorkoutProposal
    ) -> None: ...


class CoachPort(Protocol):
    async def propose(
        self, activity: Activity, report: ConditionReport
    ) -> WorkoutProposal: ...


class RepositoryPort(Protocol):
    async def save_activity(self, activity: Activity) -> None: ...
    async def save_condition(self, report: ConditionReport) -> None: ...
    async def save_proposal(self, proposal: WorkoutProposal) -> None: ...
    async def get_proposal(self, proposal_id: str) -> WorkoutProposal: ...
